### ISSUE TITLE
segmentation fault with wcc-nourine and wcc-norris algorithms

### ISSUE THREAD

**Issue by sertkaya** [sertkaya/afca#2]
https://github.com/sertkaya/afca/blob/a19c6f175b4a8c0b83e634a1afb5a2974a6c0f16/src/algorithms/connected-components/wcc.c#L40

new_component->c is not set. This causes later a segmentation fault. It happens when you run with the algorithms "wcc-nourine" or "wcc-norris" and the problem "EE-ST". I debugged for the reason and localized this error.

**Comment by objectivcp** [comment]
The issue was that new_component->c was set to bool* instead of BitSet*.
